config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'
  get 'projects/dashboard'
  post 'projects/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    validates :name, :description, presence: true
    enum state: {Propuesta: 0, En_progreso: 1, Terminado: 2}


     before_save :has_states
     def has_states
        if self.state.nil?
            self.state = "Propuesta"
        end
     end     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  http_basic_authenticate_with name: "desafiovamoscontodo", password: "XAHTJEAS23123%23", only: :dashboard
  def index
  end

  def dashboard
    if params[:state].present?
      @projects=Project.where('state = ?', params[:state])
      # @project=Project.where(states:params[:states]).all
    else
      @projects = Project.all
    end
  end

  def create
    @project = Project.create(name: params[:name], 
      description: params[:description], 
      start_on: params[:start_on], 
      finish_on: params[:finish_on], 
      state: params[:state])
      @project.save
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gestor de Proyectos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>  
  </body>
  <%= javascript_pack_tag 'application'%>
</html>

app/views/projects/create.html.erb
<% if @project.errors.any? %>
    <div id="error_explanation">
        <h2>
            <%= pluralize(@project.errors.count, "error") %>
            prohibited this post from being saved:
        </h2>
        <ul>
            <% @project.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
    <p> <%=link_to 'Intenta de nuevo', root_path %></p> 
<% else %>
    <h1>Se ha creado un proyecto con éxito, <%=link_to 'visualizalo aquí', projects_dashboard_path %></h1> 
<% end %>

app/views/projects/dashboard.html.erb
<nav class="navbar navbar-light bg-light justify-content-between">
    <h1>Dashboard de Administración<a class="navbar-brand"></a></h1>
    <form class="form-inline">
        <select name="state" id="state" class="form-control">  
            <option value="0">Propuesta</option>
            <option value="1">En progreso</option>
            <option value="2">Terminado</option>
        </select>
        <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Buscar</button>
    </form>
</nav>
<table class="table">
<div class="row">
    <div class="col -md-3"> 
        <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Descripción</th>
            <th scope="col">Fecha de comienzo</th>
            <th scope="col">Fecha de finalización</th>
            <th scope="col">Estado</th>
        </tr>
        <% @projects.each do |project| %>
        <tr>
        
            <td><%= project.name %></td>
            <td><%= project.description%></td>
            <td><%= project.start_on %></td>
            <td><%= project.finish_on %></td>
            <td><%= project.state%></td>
        <% end%>
        </tr>
   
        
    </div>
</div>
</table>
<p>Crea un nuevo proyecto <%=link_to 'aquí', root_path %> </p>

app/views/projects/index.html.erb
<h1>Crear Proyectos</h1>

<%= form_with(model: @project, url: "/projects/create", local: true) do |f|%>
    <div class=>
        <%= f.label :name, 'Nombre' %>
        <%= f.text_field :name, placeholder: 'Ingrese nombre', class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :description, 'Descripción' %>
        <%= f.text_field :description, placeholder: 'Ingrese la descripción', class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :start_on, 'Fecha de inicio' %>
        <%= f.date_field :start_on, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :finish_on, 'Fecha de finalización' %>
        <%= f.date_field :finish_on, class: 'form-control' %>
    </div>


    <div class="form-group">
        <%= f.label :state, 'Estado' %>
        <%= f.select :state, options_for_select([['Propuesta','Propuesta'],['En progreso','En_progreso'],['Terminado','Terminado']] ), {include_blank: true}, class: 'form-control' %>

    </div>

     <%= f.submit 'Guardar', class: 'btn btn-info' %>
 <% end %>
  <p>Para ver todos los proyectos dar clic <%=link_to 'aquí', projects_dashboard_path %></p>
    